# Generated by Django 2.1 on 2018-10-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181026_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
